name: customflags
description: "A Flutter SDK for feature flags, remote configuration, and runtime toggles."
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  dio: ^5.9.2
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  meta: ^1.17.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
