name: customflags
description: "A Flutter SDK for feature flags, remote configuration, and runtime toggles."
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  equatable: 2.0.8
  flutter:
    sdk: flutter
  json_annotation: 4.11.0

dev_dependencies:
  build_runner: 2.13.1
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter
  json_serializable: 6.13.1

flutter: